services:
  scraper:
    build: ./scraper
    environment:
      #- MODO_ALERTAS=generar # comentar para usar los eventos ya scrapeados
      - MODO_ALERTAS=usar_existentes
    depends_on: 
      - mongodb

  mongodb:
    image: mongo:4.4
    restart: always
    hostname: mongodb
    environment:
      - MONGO_INITDB_DATABASE=sd_db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    logging:
      driver: "none"
      
  filtro_homo:
    build: ./filtro_homo
    volumes:
      #- ./data-pig/calles:/app/salida_por_calle
      #- ./data-pig/comuna:/app/salida_por_comuna
      - ./data-pig/calles:/app/salidas_calle
      - ./data-pig/comunas:/app/salidas_comuna
    depends_on:
      - mongodb
      - scraper
